### ISSUE TITLE
Numpy import error with River

### ISSUE THREAD

**Issue by mai-n-coleman** [online-ml/river#875] opened 2022-03-12 22:54 UTC
Hi,

I read through all previous issues to make sure i have the right versions.  I have:
- numpy 1.20.1
- river 0.10.1

However I still got the "ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 232 from C header, got 216 from PyObject"

What should I do? Thank you!

**Comment by MaxHalford** [comment] 2022-03-12 22:56
Can you try `pip install numpy --upgrade`? I'm sorry, I don't know why this is still happening. Any idea @raphaelsty?

**Comment by mai-n-coleman** [comment] 2022-03-13 03:17
running pip install numpy --upgrade got my numpy version to 1.22.3 and this works. However this might mess up other libraries for me. I'm hoping it can work with numpy 1.20.1.

**Comment by raphaelsty** [comment] 2022-03-13 04:01
Hi, 

@MaxHalford I think you are referring to the issue #831 but this one is different. I should have caught that error while testing for Numpy versions.

```python
File ~/opt/miniconda3/lib/python3.8/site-packages/river/drift/adwin.py:3, in <module>
      1 from river.base import DriftDetector
----> 3 from .adwin_c import AdaptiveWindowing
      6 class ADWIN(DriftDetector):
      7     r"""Adaptive Windowing method for concept drift detection.
      8 
      9     ADWIN (ADaptive WINdowing) is a popular drift detection method with
   (...)
     62 
     63     """

File build/lib.macosx-10.9-x86_64-3.7/river/drift/adwin_c.pyx:1, in init river.drift.adwin_c()

ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 232 from C header, got 216 from PyObject
```

I managed to reproduce the error locally with Python version 3.8.12, River 0.10.1 and Numpy 1.20.1. But I was not able to reproduce the error with Google Collab and Python version 3.7.12. I'll try to find out more. :)

**Comment by MaxHalford** [comment] 2022-03-13 13:04
So we need to find a specific numpy version which works with all the major versions of Python we support. The current numpy version requirement is too loose.

**Comment by AdilZouitine** [comment] 2022-03-13 13:16
I already had this error, and it comes from the version of python used (I was using python 3.9). 
The version of python must be in 3.6 and 3.8.
What is your version of python?

**Comment by raphaelsty** [comment] 2022-03-22 14:44
@drakeleeb, You should upgrade Numpy with `pip install numpy --upgrade`

**Comment by drkoocha** [comment] 2022-04-14 14:14
Hi, get the same error with

**Comment by drkoocha** [comment] 2022-04-14 14:20
Hi, I got the error 
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 232 from C header, got 216 from PyObject
with updated numpy 1.21.5
unistalled numpy and river and reinstalled them few times
How to make river work?
Thanks

**Comment by hoanganhngo610** [comment] 2022-04-14 16:58
@drkoocha What version of Python are you using. This seems to be the same version that @raphaelsty has been able to reproduce locally. Moreover, how did you install River (through `pip` or with the latest version on Github)?

**Comment by drkoocha** [comment] 2022-04-15 01:52
thanks @hoanganhngo610 
I have Python 3.8.10
installed River through pip

**Comment by raphaelsty** [comment] 2022-04-15 08:09
@drkoocha Could you try `pip install numpy --upgrade` ? :)

**Comment by drkoocha** [comment] 2022-04-16 03:42
@raphaelsty tried that, did not help :(

**Comment by smastelini** [comment] 2022-04-16 08:33
Hi @drkoocha and @raphaelsty. I've recently had problems with numpy and River, but only after installing matplotlib. I think there must be some conflicts between the dependency trees. In the end, I installed matplolib in a different virtual environment and everything worked.

**Comment by gbolmier** [comment] 2022-04-17 08:03
@drkoocha can you try with `numpy>=1.22.0`?

**Comment by drkoocha** [comment] 2022-04-18 07:30
@gbolmier tried it, uninstalled/installed numpy, matplotlib, river twice -- still not working

**Comment by MaxHalford** [comment] 2022-04-18 08:38
If I were you I would reset my Python environment @drkoocha

**Comment by gbolmier** [comment] 2022-04-20 15:02
@drkoocha what is the `numpy` version you're using when it's failing? Could you please provide a snippet to reproduce the failing environment, e.g.:

```shell
conda create -n river python==3.8.10 river matplotlib==X.Y.Z
```

**Comment by drkoocha** [comment] 2022-04-21 10:58
@gbolmier I work with poetry instead of conda. 
Python 3.8.10
libraries from `dir list`
```
matplotlib                    3.5.1
matplotlib-inline             0.1.3
numpy                         1.21.5
river                         0.10.1
```
Other libraries of interest?

**Comment by drkoocha** [comment] 2022-04-21 11:08
@gbolmier full error notice:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [3], in <module>
      5 from matplotlib import pyplot as plt
      6 import seaborn as sns
----> 7 import river
      8 import skmultiflow
      9 import os

File c:\..\.venv\lib\site-packages\river\__init__.py:9, in <module>
      1 """
      2 river is a library for incremental learning. Incremental learning is a machine learning regime
      3 where the observations are made available one by one. It is also known as online learning,
   (...)
      7 scikit-learn, enough so that users who are familiar with scikit-learn should feel right at home.
      8 """
----> 9 from . import (
     10     anomaly,
     11     base,
     12     cluster,
     13     compat,
     14     compose,
     15     datasets,
     16     drift,
     17     dummy,
     18     ensemble,
     19     evaluate,
     20     facto,
     21     feature_extraction,
     22     feature_selection,
     23     imblearn,
     24     linear_model,
     25     metrics,
     26     misc,
     27     model_selection,
     28     multiclass,
     29     multioutput,
     30     naive_bayes,
     31     neighbors,
     32     neural_net,
     33     optim,
     34     preprocessing,
     35     proba,
     36     reco,
     37     rules,
     38     stats,
     39     stream,
     40     time_series,
     41     tree,
     42     utils,
     43 )
     44 from .__version__ import __version__  # noqa: F401
     45 from .datasets import synth

File c:\..\.venv\lib\site-packages\river\anomaly\__init__.py:13, in <module>
      1 """Anomaly detection.
      2 
      3 Estimators in the `anomaly` module have a bespoke API. Each anomaly detector has a `score_one`
   (...)
     10 
     11 """
     12 from .base import AnomalyDetector
---> 13 from .hst import HalfSpaceTrees
     14 from .svm import OneClassSVM
     15 from .threshold import ConstantThresholder, QuantileThresholder

File c:\..\.venv\lib\site-packages\river\anomaly\hst.py:7, in <module>
      4 import typing
      6 from river import base
----> 7 from river.tree.base import Branch, Leaf
      9 from .base import AnomalyDetector
     11 __all__ = ["HalfSpaceTrees"]

File c:\..\.venv\lib\site-packages\river\tree\__init__.py:55, in <module>
     53 from . import splitter
     54 from .extremely_fast_decision_tree import ExtremelyFastDecisionTreeClassifier
---> 55 from .hoeffding_adaptive_tree_classifier import HoeffdingAdaptiveTreeClassifier
     56 from .hoeffding_adaptive_tree_regressor import HoeffdingAdaptiveTreeRegressor
     57 from .hoeffding_tree_classifier import HoeffdingTreeClassifier

File c:\..\.venv\lib\site-packages\river\tree\hoeffding_adaptive_tree_classifier.py:7, in <module>
      5 from .hoeffding_tree_classifier import HoeffdingTreeClassifier
      6 from .nodes.branch import DTBranch
----> 7 from .nodes.hatc_nodes import (
      8     AdaBranchClassifier,
      9     AdaLeafClassifier,
     10     AdaNomBinaryBranchClass,
     11     AdaNomMultiwayBranchClass,
     12     AdaNumBinaryBranchClass,
     13     AdaNumMultiwayBranchClass,
     14 )
     15 from .splitter import Splitter
     18 class HoeffdingAdaptiveTreeClassifier(HoeffdingTreeClassifier):

File c:\..\.venv\lib\site-packages\river\tree\nodes\hatc_nodes.py:5, in <module>
      2 import math
      3 import typing
----> 5 from river.drift import ADWIN
      6 from river.utils.skmultiflow_utils import check_random_state, normalize_values_in_dict
      8 from ..utils import do_naive_bayes_prediction

File c:\..\.venv\lib\site-packages\river\drift\__init__.py:10, in <module>
      1 """
      2 Concept Drift Detection.
      3 
   (...)
      7 
      8 """
---> 10 from .adwin import ADWIN
     11 from .ddm import DDM
     12 from .eddm import EDDM

File c:\..\.venv\lib\site-packages\river\drift\adwin.py:3, in <module>
      1 from river.base import DriftDetector
----> 3 from .adwin_c import AdaptiveWindowing
      6 class ADWIN(DriftDetector):
      7     r"""Adaptive Windowing method for concept drift detection.
      8 
      9     ADWIN (ADaptive WINdowing) is a popular drift detection method with
   (...)
     62 
     63     """

File build\lib.win-amd64-3.7\river\drift\adwin_c.pyx:1, in init river.drift.adwin_c()

ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 232 from C header, got 216 from PyObject
```

**Comment by MaxHalford** [comment] 2022-04-21 16:10
@gbolmier should we add that requirement to our `setup.py`? We could also maybe reimplement ADWIN in plain Python.

**Comment by gbolmier** [comment] 2022-04-21 16:46
Yeah, apparently `1.20.X` is working so I think we should just exclude `1.21.X`

**Comment by smastelini** [comment] 2022-04-21 16:56
I am against using pure python in ADWIN if possible. @jacobmontiel reported up to 10x faster processing times in some ensembles back in the day.

**Comment by hoanganhngo610** [comment] 2022-04-22 01:48
Totally agree @smastelini. C has proven to be much much faster than pure Python in many of our cases, which I believe has no reason to be changed.

**Comment by MaxHalford** [comment] 2022-04-22 08:23
No problem! I would like us to fix this numpy issue though.

**Comment by raphaelsty** [comment] 2022-04-22 10:19
What do you think a bou a try / except on import ?

**Comment by pillarxyz** [comment] 2022-05-02 15:44
i had the same issue, for me river worked after downgrading to 1.16.6

**Comment by gbolmier** [comment] 2022-05-02 18:07
Hey @pillarxyz, what `numpy` version did you have an issue with? Have you tried with `1.20.X` or `1.22.X`?

**Comment by pillarxyz** [comment] 2022-05-03 10:40
> Hey @pillarxyz, what `numpy` version did you have an issue with? Have you tried with `1.20.X` or `1.22.X`?

it was 1.22.3

**Comment by gbolmier** [comment] 2022-05-04 09:37
@pillarxyz could you provide a snippet to reproduce the failing environment? I don't have any issue on my side with the following:

```shell
$ conda create -n river python==3.9.12
$ conda activate river
$ pip install river==0.10.1 numpy==1.22.3
$ python                                                                                     
>>> import river
```

**Comment by MaxHalford** [comment] 2022-05-28 13:11
I've added `numpy>=1.22` to `setup.py`. Closing this.

**Closed by MaxHalford** 2022-05-28 13:11 UTC
