### ISSUE TITLE
You cannot use Hoeffding Tree Regressor as the leaf model of Adaptive Random Forest's trees

### ISSUE THREAD

**Issue by JPalm1** [online-ml/river#401] opened 2020-11-27 10:32 UTC
## Versions

**river version**: 0.1.0 + PR #394 
**Python version**: 3.7.1
**Operating system**: Windows 10 Enterprise v1803

## Describe the bug

Found this morning. Trying to build an ARFR + HT/HAT as the `leaf_model` and I get the following exception: 

"TypeError: learn_one() takes 3 positional arguments but 4 were given" @ Line 133 `htr_nodes.py`

Is this excpected (ie is a forest of HT regressors not applicable)? Will have a step through my code now, but just thought I'd flag it.

## Steps/code to reproduce

```py
from river import datasets
from river import evaluate
from river import metrics
from river import ensemble, tree
from river import preprocessing

dataset = datasets.TrumpApproval()
r = tree.HoeffdingTreeRegressor(grace_period=50, leaf_prediction='adaptive',model_selector_decay=0.7)
model = (
    preprocessing.StandardScaler() |
    ensemble.AdaptiveRandomForestRegressor(n_models=3, seed=42, leaf_model=r)
)

metric = metrics.MAE()

evaluate.progressive_val_score(dataset, model, metric)
```

**Comment by smastelini** [comment] 2020-11-27 11:41
Hi @JPalm1.

> Is this excpected (ie is a forest of HT regressors not applicable)? 

The error happens because of this line.

https://github.com/online-ml/river/blob/4466595fcae1d6b6843dc874637f89354bacc43b/river/tree/hoeffding_tree_regressor.py#L202

The trees were designed so that if you want to use sample weights, you should specifically state that, i.e., using a keyword argument. So, in short, you currently cannot create an RF where the trees' leaves are also incremental decision trees.

I am not entirely convinced of the effectiveness of this approach. But we might consider making this possible in the future. I need to do some tests to check how this might impact the models.

**Comment by JPalm1** [comment] 2020-12-01 11:38
Hi @smastelini , thanks for the reply! I wasn't sure whether it was due to an issue in the codebase or a restriction in the behavior available, so I appreciate the explanation. In a few papers I have read, I have seen the HT be used in an adaptive random forest, so it could be a good potential feature, although I don't know the overhead cost needed to implement such a feature.

**Comment by smastelini** [comment] 2020-12-01 12:51
Hi @JPalm1, thanks for the response. I think now I see your point. Maybe you are confusing some concepts. Let me explain:

>  In a few papers I have read, I have seen the HT be used in an adaptive random forest, so it could be a good potential feature, although I don't know the overhead cost needed to implement such a feature.

The adaptive random forest indeed uses HT as its base model. In other words, the forest is composed of multiple HTs. They work slightly differently than the vanilla HT because each leaf node only monitors a subset of features. Indeed, Random Forest (online and batch ones) work by subsampling instances (with replacement, i.e., bagging) and features (without replacement).
Now, HT regressors may use prediction models in their leaves to compute predictions. That's why FIMT-DD, Hoeffding Tree Regressor, M5 (for batch applications), and so on are called "model trees". Typically a linear model is trained in each leaf to provide responses. `river` goes one step further and gives the users the freedom to pick which model they want to use in the tree leaves (be it a linear model or not).

In your example, you're trying to make the leaf models of HTs in a forest use other trees to make predictions. While this is theoretically possible, I do not see a clear reason to choose this strategy. Here go some reflections:

- HTs perform split attempts at each `grace_period` interval
- If we use a tree as the leaf model of another tree, the predictor will probably be always a single node (i.e., a tree with only the root) or perform only a few splits
    - As the leaf carrying the tree predictor monitors more data, it is going to split, and the learning process will restart in its newly added descendants
    - The leaf's tree (that's weird, hahaha) could be copied to the newly created branches, but even so, I am not convinced of the effectiveness of this approach.

Note that if we put a tree as the predictor of a leaf, this tree never splits (because the outer tree might split first), and the "inner" tree uses a linear model; we are actually just adding overhead without clear benefits. I mean, why not using a linear model directly?

On the other hand, if you do not want the HTs to process a subset of features per node and continue using bagging, you should check one of the Bagging variants available in the `ensemble` submodule.

**Comment by smastelini** [comment] 2021-01-28 13:17
Closing, since the scope of the issue is related to a design choice limitation.

**Closed by smastelini** 2021-01-28 13:17 UTC
Labels: Type: Discussion
