### ISSUE TITLE
Understanding predict_many & forecast

### ISSUE THREAD

**Issue by athammad** [online-ml/river#430] opened 2020-12-30 12:04 UTC
Hi,

I have 8 years and 6 months of daily weather data (temperature, humidity, rain, wind, rain etc.). In the last 1 year and 6 months, I don't have values of rain. Hence, I would like to train a model based on the first 7 years of complete data and predict rain's missing values. I really like your project philosophy, and I believe this is the most suitable approach to solve time series prediction problems.

**I might be mistaken**, but it seems that this is not the right library for my case based on the documentation and the examples provided. 
I have tried to follow the documentation of the [`HoeffdingTreeRegressor`](https://riverml.xyz/latest/api/tree/HoeffdingTreeRegressor/). Still, I am confused about using the functions `predict_many`, and `forecast` that I assume should be the right functions for my case.

Any suggestions are welcome.

Best wishes

**Comment by MaxHalford** [comment] 2020-12-31 10:47
Hello there, thanks for the interest.

In my opinion this is not the right tool for your task. The period of 1 year and 6 month is too long to frame things as a time series problem. If I were you, I would frame this as a straightforward batch learning problem: train on the first 7 years, then predict the missing rain values. 

It's a classic blunder to believe that time series data has to be approached with a time series model. I really believe that here you don't have to worry too much about the temporal aspect of your data. You can add some features like the average amount of rain for any given day, computed in a windowed fashion.

![Classic+Blunders+meme](https://user-images.githubusercontent.com/8095957/103407164-d0ad6b80-4b5d-11eb-9427-6de8f929ccfb.png)

**Comment by slakm09** [comment] 2021-02-10 19:15
Hi Max,

Thak you for your effort answering all those questions.

I also have a similar challenge: 3 years of hourly weather data (temperature, humidity, rain, wind, rain etc.) and would like to predict temperature for the next 12 hours.
I'm using Creme library, because we'd like to have a permanent learning model. First training-prediction cycle is based on 3 years of data and results are OK (MAE is 0.22). This is the part of the code:

# model evaluation function
def evaluate_model(model_i): 
    metric = metrics.Rolling(metrics.MAE(), 12)

    for x, y in dataset:
        y_pred = model_i.predict_one(x)
        model_i.fit_one(x, y)
        metric = metric.update(y, y_pred)        

# model definition
subset = compose.Select('ST', 'SST', 'AT', 'TD', 'IR', 'SF', 'FC', 'Generated_hour', 'DateTime_hour')
scaler = preprocessing.StandardScaler()
learn = linear_model.LinearRegression(
    intercept_lr=0,
    optimizer=optim.SGD(0.010)
)
model = subset | scaler | learn
model = time_series.Detrender(regressor=model, window_size=12)

# learning proces
dataset = stream.iter_csv(
    'C:/TEMP/i-RBF/River/examples/09022021/Data_Merge_2018-2020_filtered5.csv',
    converters={
        'MinuteForecast': int,
        'Generated_hour': int,
        'DateTime_hour': int,
        'ST': float,
        'SST': float,
        'AT': float,
        'TD': float,
        'IR': float,
        'SF': float,
        'FC': float,
        'Mes_Value': float
    },
    parse_dates={'DateTime': '%Y-%m-%d %H:%M:%S'},
    target='Mes_Value'
)
evaluate_model(model)

In the next step we'd like to predict target values for the next 12 hours:

# prediction process
dataset_METRo = stream.iter_csv(
    'C:/TEMP/i-RBF/River/examples/Data_METRo_jan2021a.csv',
    converters={
        'ST': float,
        'SST': float,
        'AT': float,
        'TD': float,
        'IR': float,
        'SF': float,
        'FC': float
    }
)
for (x, y) in dataset_METRo:
    # make predictions on the current set of features
    predict = model2.predict_one(x)
    print(x, predict)

Prediction results are really bad and I don't know if my approach is OK, if features and label are properly selected.
I am also attaching Jupyter source.

Thanks for any advise or comment.

**Comment by slakm09** [comment] 2021-02-11 07:39
Uploding source code.
[METRo-time-series_09022021.zip](https://github.com/online-ml/river/files/5963618/METRo-time-series_09022021.zip)

**Comment by MaxHalford** [comment] 2021-02-16 18:33
Hey @slakm09 I'm closing this issue. You can open a [discussion](https://github.com/online-ml/river/discussions). Please try to clearly explain what you're trying to do and formulate some questions. To be honest none of us has the time to deep dive into your code and understand what you're doing. We can however answer specific questions.

**Closed by MaxHalford** 2021-02-16 18:33 UTC
Labels: Type: Discussion
