### ISSUE TITLE
RandomForest Modelling Error

### ISSUE THREAD

**Issue by shaksham95** [online-ml/river#251] opened 2020-03-03 07:40 UTC
Hello.

I have a business problem and a model to solve that problem. Now, I am trying to incorporate online learning into the process. For that, I have developed a pipeline using creme, and I am using the Random Forest Classifier for modeling purposes.

The issue that I am facing is, the model works fine for some number of observations and then breaks down at some nth observation (see the screenshot).

![image](https://user-images.githubusercontent.com/7498849/75752896-9e6d8a80-5d4f-11ea-9ae8-78b0751c0353.png)

![image](https://user-images.githubusercontent.com/7498849/75752909-a6c5c580-5d4f-11ea-9a9f-2b48dac14ae1.png)

The pipeline prepares the data into a format that is required by creme for training and evaluating. I am using the following steps to train/test the model;

![image](https://user-images.githubusercontent.com/7498849/75753009-d4127380-5d4f-11ea-80b4-239d2264e15f.png)

Can you please help why is it breaking down for some random observations?

Any leads would be highly appreciated.

Thanks
Shaksham

**Comment by MaxHalford** [comment] 2020-03-03 07:55
Hey there. I can spot a `nan` value for the `tfidf_train_word_match` field, maybe that's it?

To be honest I've already had this kind of issue with `utils.Histogram`, but I never figured out why it bugged. Let's get it fixed in this issue! Ideally, could you provide the entire code and dataset you're using? Then I can debug it and fix the problem myself.

**Comment by shaksham95** [comment] 2020-03-03 08:57
Hey @MaxHalford,

Unfortunately, I cannot share the data or the code since it's client data and is confidential. Also, the modeling process is internal. 

I also suspected that maybe due to the presence of `nan` values, the error is coming, but all the observations before the nth observation have the same values (`nan`) for `tfidf_train_word_match ` field. So, I think we can rule that possibility out.

Looking forward to the new release, Any ideas when that might happen?

**Comment by MaxHalford** [comment] 2020-03-03 09:17
No worries that's totally understandable! I'll run it on some other data and try to reproduce the error.

As for the next release, it's probably going to happen this week.

**Comment by shaksham95** [comment] 2020-03-03 10:23
You use [quora question-answer](https://www.kaggle.com/c/quora-question-pairs) pairs as your dataset. It's similar to what I have used.

**Comment by MaxHalford** [comment] 2020-03-03 14:03
@shaksham95 quick question, what version of Python are you using?

**Comment by MaxHalford** [comment] 2020-03-03 14:29
Actually I just remembered that I believe I fixed this since version `0.4.4`. Would you be so kind as to install the development branch and see if the bug persists? You can that via `pip install git+https://github.com/creme-ml/creme`.

**Comment by shaksham95** [comment] 2020-03-04 03:36
I just tried installing the development branch, but it ran into the following error:

![image](https://user-images.githubusercontent.com/7498849/75842761-45f1c800-5df7-11ea-95d4-79b504932f8a.png)

Python version: 3.7.4
creme version: 0.4.4

**Comment by MaxHalford** [comment] 2020-03-04 08:15
Yeah this is because `creme` requires Cython and a GCC compiler to install from source. The problem comes from your setup. I think you should start by installing the software in the link at the end of your error message.

**Comment by shaksham95** [comment] 2020-03-04 08:27
Okay, is this a new requirement for the code in the development branch? I have previously installed creme but didn't receive any such error messages.

**Comment by MaxHalford** [comment] 2020-03-04 08:35
Let me explain haha.

When you do `pip install creme`, it installs precompiled version of `creme` (called a wheel). In this case you don't need to compile the Cython modules yourself. 

When you do `pip install git+https://github.com/creme-ml/creme`, you're installing the development version, for which no wheels have been built. Therefore, you need to be able to compile Cython modules when you install the development version.

Sorry for making you go through all these hoops!

**Comment by shaksham95** [comment] 2020-03-04 08:55
Sorry for asking such a stupid question, @MaxHalford 😅, and thank you for explaining the difference.

I will try setting up the required libraries and will then run the code and check if it still breaks.

**Comment by MaxHalford** [comment] 2020-03-04 09:00
No man it's far from stupid! Good luck.

**Comment by shaksham95** [comment] 2020-03-05 09:00
Hey @MaxHalford ,

I have a quick question. In scikit learn, there are some algorithms that do incremental learning. So, what's the difference between those and creme?

**Comment by MaxHalford** [comment] 2020-03-05 15:52
The algos from `sklearn` that support incremental learning are mostly meant for mini-batch learning. If you benchmark `creme` and `sklearn` on a pure streaming context where the observations arrive one by one, then `creme` is much faster. Also, `sklearn` assumes that you're always going to have the same number of features. `creme` is more focused on handling observations one by one, and deals with dictionaries, which allows you to drop and add features as you wish.

**Comment by shaksham95** [comment] 2020-03-06 03:23
Thank you for this detailed answer :)

**Comment by shaksham95** [comment] 2020-03-16 03:46
Hey @MaxHalford ,

With the recent release (version 0.5.0) is the bug fixed? I tried but it is still giving me the same error.

**Comment by MaxHalford** [comment] 2020-03-16 07:43
It should have been fixed but I guess it isn't... As I said I wasn't able to reproduce the error so I can't move forward.

**Closed** 2020-11-24 08:09 UTC
Labels: Type: Bug
