### ISSUE TITLE
Error with AdaptiveRandomForest all nominal attributes

### ISSUE THREAD

**Issue by jppereze** [online-ml/river#446] opened 2021-01-20 02:56 UTC
**river**: 1.0 (latest version of river (installed with pip install git+https://github.com/online-ml/river --upgrade))
**python**:3.8.5
**Operating System**:Ubuntu 20.04

## Description
While testing a full nominal dataset (all attributes treated as nominal attributes), the AdaptiveRandomForestClassifier breaks with the following error:

```
...packages/river/tree/_attribute_test/nominal_attribute_multiway_test.py in add_new_branch(self, att_val)
     58         """
---> 58         new_branch_id = max(self._branch_mapping.values()) + 1
     59         self._branch_mapping[att_val] = new_branch_id
     60         self._reverse_branch_mapping[new_branch_id] = att_val

ValueError: max() arg is an empty sequence_
```

## Steps/code to reproduce
This happens with an all-nominal dataset, after a couple of thousands of learn cycles.
Something like this seem to have fixed the issue but I'm not sure if the behaviour of the RF is now going to be the expected:

`_new_branch_id = max(self._branch_mapping.values()) + 1 if len(self._branch_mapping.keys())>0 else 1
`
If you confirm the fix is OK I can push it or whatever works... happy to help as much as needed.

I cannot share the dataset, as you may understand but I'm happy to test any other alternative to the provided fix.

**Comment by smastelini** [comment] 2021-01-20 13:06
Hi @jppereze, thanks for reporting that.

Your solution could avoid the error with a minor modification. However, what intrigues me is why the error happens at all.

The tree creates a list of existing branches when it performs a split, i.e., observed category values. In your case, this list would have all the observed categories for the split feature. I am not sure why this list would be empty to trigger the mentioned error.

This deserves more investigation. Rather than adding a workaround, I would prefer to find the root cause. So let's dig deeper into this problem.

Does your data have `None`?

**Comment by jppereze** [comment] 2021-01-20 15:32
Hi @smastelini, thanks for the prompt reply. I could not agree more with the approach of finding the root cause. There might be some None values in the data. If that is the case, should I treat the data differently?. Thanks again.

**Comment by smastelini** [comment] 2021-01-20 17:25
Hi @jppereze. Since dictionaries are sparse by nature, if a feature value is `None`, you can safely remove this feature from the dictionary without breaking the learning models.

**Comment by smastelini** [comment] 2021-01-28 13:20
I will close this one, as the error seems to be related to the data rather than the models. If new pieces of evidence appear, we can reopen this discussion.

**Closed by smastelini** 2021-01-28 13:20 UTC
Labels: Type: Discussion
