### ISSUE TITLE
Question on MacroAverage metric is not compatible with PyTorch2RiverRegressor

### ISSUE THREAD

**Issue by beinathan** [online-ml/river#952] opened 2022-06-06 06:53 UTC
Hi all, sorry to bother you again. I'm trying to build a multi-output model with PyTorch2RiverRegressor. When I try to pre-train the model, I get the following error, is there a way to fix it? Thanks for your reply.
**ValueError: MacroAverage metric is not compatible with PyTorch2RiverRegressor**

**Comment by gbolmier** [comment] 2022-06-06 16:39
Hi @beinathan, would you mind providing a minimalist snippet to reproduce the error?

**Comment by beinathan** [comment] 2022-06-07 13:20
[test.zip](https://github.com/online-ml/river/files/8853495/test.zip)
Hey! The main code is included here, thank you for your patience.

**Comment by gbolmier** [comment] 2022-06-10 23:31
The error might be due to an old `river` version. I created a couple of PR (#962, online-ml/river-extra#2) to relax version contraints between `river` and `river-extra` which was forcing us to use `0.8.0`.

Let's try again from a fresh environment after the PRs are merged.

**Comment by beinathan** [comment] 2022-06-16 09:26
Sorry for not replying sooner, I tried to download the latest version of river, where the file setup.py has been updated, but the problem is still not solved, and the minimum test case is still the same as before, thanks again for your reply.

**Comment by MaxHalford** [comment] 2022-06-16 09:28
Are you ok taking this @gbolmier? If not I can't take a look.

**Comment by gbolmier** [comment] 2022-06-16 09:52
Yes, I'm on it 👍

**Comment by MaxHalford** [comment] 2022-06-16 12:33
Mmm I see now.

It's a special in the sense that it can be a regular single-target regressor, as well as a multi-output one, dependending on `build_fn`. It all depends  I guess making `PyTorch2RiverRegressor` inherit from `base.MultiOutputMixin` in any case is ok. Especially if it's in `river-extra`.

Can I let you make that change?

**Comment by gbolmier** [comment] 2022-06-16 12:38
Yep, I'll make the change 👌

**Comment by gbolmier** [comment] 2022-06-16 15:02
@beinathan with the last change made in `river-extra` it now works for me. Until a new release of `river-extra` is made to pypi, you can install the latest version from github with:

```shell
pip install "river-extra @ git+https://git@github.com/online-ml/river-extra.git"
```

**Closed** 2022-06-16 15:03 UTC
